os: linux
dist: xenial

language: generic

cache:
  directories:
    - $HOME/.m2

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.447.sh
  - chmod +x linux-install-1.10.1.447.sh
  - sudo ./linux-install-1.10.1.447.sh

before_script:
  - env | sort

script:
  - ./manage.sh build-devenv
  - ./manage.sh run-frontend-tests
  - ./manage.sh run-backend-tests
  - ./manage.sh build-frontend
  - ./manage.sh build-backend
  - ./manage.sh build-exporter
  #- ./manage.sh run

after_script:
  - docker images

notifications:
  email: false

env:
  - NODE_VERSION=10.16.0
