version: "3"

volumes:
  backend_m2:
  backend_data:
  db_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.12.0/24

services:
  uxdb:
    image: postgres:11
    container_name: uxdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_DB=uxbox
      - POSTGRES_USER=uxbox
      - POSTGRES_PASSWORD=uxbox_postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro

  uxbackend:
    image: uxbox-production-backend:latest
    container_name: uxbackend
    # restart: always
    depends_on:
      - uxdb
    ports:
      - 6060:6060
    volumes:
      - backend_data:/srv/uxbox/resources/public
      - backend_m2:/root/.m2
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro

    environment:
      # HTTP setup
      - UXBOX_HTTP_SERVER_DEBUG=false
      - UXBOX_MEDIA_URI="/media/"
      - UXBOX_ASSETS_URI="/static/"
      # Database setup
      - UXBOX_DATABASE_USERNAME="uxbox"
      - UXBOX_DATABASE_PASSWORD="uxbox_postgres_password"
      - UXBOX_DATABASE_NAME="uxbox"
      - UXBOX_DATABASE_SERVER="uxdb"
      - UXBOX_DATABASE_PORT=5432
      # Mail setup
      - UXBOX_EMAIL_REPLY_TO="no-reply@uxbox.io"
      - UXBOX_EMAIL_FROM="no-reply@uxbox.io"
      # STMP setup
      - UXBOX_SMTP_HOST="localhost"
      - UXBOX_SMTP_PORT=25
      - UXBOX_SMTP_USER="uxbox"
      - UXBOX_SMTP_PASSWORD="youshouldoverwritethiswithsomethingelse"
      - UXBOX_SMTP_SSL=false
      - UXBOX_SMTP_TLS=false
      - UXBOX_SMTP_ENABLED=false
      # Security setup
      - UXBOX_SECRET="foobar"

  uxfrontend:
    image: uxbox-production-frontend:latest
    container_name: uxfrontend
    #hostname: uxbox.io
    restart: always
    depends_on:
      - uxbackend
    ports:
      - 8080:8080
    volumes:
      - backend_data:/srv/uxbox/
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
